### ISSUE TITLE
`POST /entries` always fails

### ISSUE THREAD

**Issue by ocboogie** [eed-web-application/elog-plus#126]
```
{
  "title": "New entry",
  "text": "",
  "logbooks": ["64dbf75656dcd74ec2358996"],
  "attachments": [],
  "tags": []
}
```
 to `POST /entries` where `64dbf75656dcd74ec2358996` is the id of a logbook responds with
```
{
    "timestamp": "2023-08-16T18:44:11.907+00:00",
    "status": 404,
    "error": "Not Found",
    "path": "/v1/entries",
    "errorCode": -1,
    "errorMessage": "The Entry has not been found",
    "errorDomain": "LogbookService:getLogbookByName"
}
```

**Comment by bisegni** [comment]
for the entry creation this api is not more called the logbook is fetched with LogbookService::getLogbook and it fire the LogbookNotFound that I had fixed the text with: "The logbooks has not been found".So I think you have not build the last docker image
