### ISSUE TITLE
Add query parameter `includeSupersededBy` to the `GET /entries/{entryId}` endpoint

### ISSUE THREAD

**Issue by ocboogie** [eed-web-application/elog-plus#137]
Create the query parameter `includeSupersededBy` to the `GET /entries/{entryId}` endpoint such that if the entry with id `entryId` has been superseded, then the `EntrySummaryDTO` of the entry that superseded is attached to the output under the field name `supersededBy`. If the entry with id `entryId` has not been superseded, then `supersededBy` will be null.

**Comment by ocboogie** [comment]
Bump @bisegni

**Comment by bisegni** [comment]
it is done but i a PR that i cannot submit

**Comment by bisegni** [comment]
i think i forgot to do it , ok it is in the list
