### ISSUE TITLE
`PUT /logbooks/{id}` not deleting or creating new authorizations

### ISSUE THREAD

**Issue by ocboogie** [eed-web-application/elog-plus#180]
We have a logbook with the following:
```json
{
    "id": "65ca759969873c5f60821bbe",
    "name": "accel",
    "tags": [],
    "shifts": [],
    "authorizations": [
        {
            "id": "65ca7af069873c5f60821be8",
            "authorizationType": "Write",
            "owner": "user1@slac.stanford.edu",
            "ownerType": "User",
            "resource": "/logbook/65ca759969873c5f60821bbe"
        }
    ],
    "authenticationTokens": []
}
```
When trying to delete the authorization by executing `PUT /logbooks/65ca7af069873c5f60821be8` with the payload
```json
{"id":"65ca759969873c5f60821bbe","name":"accel","tags":[],"authorization":[],"shifts":[]}
```
we get a 201 (see #181 ). However, the authorization is not deleted which can be seen by a request to `GET /logbooks ?includeAuthorizations=true` for example.

When trying to create a authorization by executing `PUT /logbooks` with the payload
```json
{
  "id": "65ca759969873c5f60821bbe",
  "name": "accel",
  "tags": [],
  "authorization": [
    {
      "id": "65ca7af069873c5f60821be8",
      "authorizationType": "Write",
      "owner": "user1@slac.stanford.edu",
      "ownerType": "User",
      "resource": "/logbook/65ca759969873c5f60821bbe"
    },
    {
      "owner": "user2@slac.stanford.edu",
      "authorizationType": "Read",
      "ownerType": "User"
    }
  ],
  "shifts": []
}
```
we get a 201 again, but the authorization is not created.

**Comment by bisegni** [comment]
i create a specific test but i cannot reproduce i made this steps:

- create logbook
- update logbook with auth
- get full logbook and check the presence of auth
- update the logbook with emptyList on auth
- get full logbook and assert on authorization list size==0
and all work, try to retet with last release of backend
