### ISSUE TITLE
Implement previews

### ISSUE THREAD

**Issue by ocboogie** [eed-web-application/elog-plus#20]
Suggested endpoint: `GET /attachments/{id}/preview.webp` or `GET /attachments/{id}/preview.jpeg`.
I would prefer [`webp`](https://developers.google.com/speed/webp) as it is smaller and widely supported, however if that's not possible, jpeg would also work.

**Comment by bisegni** [comment]
The AttachmentDTO didn't has anymore the fled 'hasPreview' ti has been replace by more expresive one called 'previewState': it can have the following value(as string type):

- Waiting, the attachment is waiting to be processed
- Processing, the attachment is being processing 
- Error, there will be some error and it will be retried
- PreviewNotAvailable, the image format don't permit to generate a JPEG preview
- Completed, the JPEG preview has been generated and it is available
