### ISSUE TITLE
`referencedBy` is not updated when creating an entry that references another

### ISSUE THREAD

**Issue by ocboogie** [eed-web-application/elog-plus#206]
When making an entry A that references an existing entry B by including a link to entry B in the body of entry A, entry B's `referencedBy` is not updated. For example, suppose we create an entry A with body
 ```html
 <a href="http://localhost:4567/elog/entry/{entry B ID}">Entry B</a>
 ```
using `POST /entries`. Then, if we were to `GET /entries/{entry B id}`, we expect `referencedBy` to be a list that includes the ID of entry A. However, it is not. This may work in production, as this functionality may depend on the URL of the Elog, however in development it does not work. 

We could have the backend just look for IDs of other entries, ignoring the rest of the URL entirely. Or, we could tell the backend what the frontend URL is through environment variables or Docker arguments. I am open to ideas on this.

**Comment by bisegni** [comment]
@ocboogie this below was the format of the reference in the old style:
```
String ref_one = "<href=\"http://localhost/%s\">".formatted(newLogID1);
String ref_two = "<href=\"http://localhost/%s\">".formatted(newLogID1);
```

so i this point i need to change using this as prefix: `elog/entry/{entry B ID}`, it's ok?
