### ISSUE TITLE
Validate `members` on `PUT /groups/{groupId}`

### ISSUE THREAD

**Issue by ocboogie** [eed-web-application/elog-plus#242]
`PUT /groups/{groupId}` with
```json
{
  "members": [
    "blah",
    "invalid"
  ]
  // ...
}
``` 
is successful. However, when `GET /groups/{groupId}?includeMembers=true` responds with
```json
{
  "members": [
    null,
    null
  ]
  // ...
}
```

**Comment by ocboogie** [comment]
This is why the "EED-WEB-Developer" group is broken right now: https://accel-webapp-dev.slac.stanford.edu/elog/admin/groups/66a955cf21a99b78a1178dc8

**Comment by bisegni** [comment]
member need to be user email not the ID
```
{
  "members": [
    "trzope",
    "abs",
    "bisegni",
    "tiffany",
    "boogie"
  ],

}
```
