### ISSUE TITLE
improvement for tags management

### ISSUE THREAD

**Issue by bisegni** [eed-web-application/elog-plus#41]

**Comment by bisegni** [comment]
@ocboogie I started the branch fro improve the tags management.
I think fomenting like that:

- api for save a tag
- api for retrieve all tags
- when a tags are saved into a log each one are checks if contained into the tags-collection. In this way we are sure that only available tags are saved into logs

**Comment by ocboogie** [comment]
Actually, I think we only need one endpoint: to retrieve all tags. Then, the only way to create tags would be through creating logs, which I think is the only use case. There isn't a need, at least on the front end, for an endpoint to create tags. What do you think?
