### ISSUE TITLE
Give a recognizable error when uploading attachments that are too big

### ISSUE THREAD

**Issue by ocboogie** [eed-web-application/elog-plus#45]
Right now, if you try to upload an attachment that's too big, the API responds with an internal server error:
```json
{
    "timestamp": "2023-07-07T18:47:58.846+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "path": "/v1/attachment",
    "org.springframework.web.multipart.MaxUploadSizeExceededException": "org.springframework.web.multipart.MaxUploadSizeExceededException: Maximum upload size exceeded"
}
```
However, I can't detect that the attachment is too big from this error which is necessary, since we want to display to the user that attachment is too big.

**Comment by bisegni** [comment]
we need to discuss this

**Comment by bisegni** [comment]
can the size be detected before start the upload, using some javascript function?
