### ISSUE TITLE
Why is `/v1/search` POST?

### ISSUE THREAD

**Issue by ocboogie** [eed-web-application/elog-plus#5]
I would expect it to be GET, as it does not create any new data and is idempotent (as far as I can tell).

**Comment by bisegni** [comment]
good observation, will modify on get ASAP

**Comment by bisegni** [comment]
@ocboogie we need to check if the query could be greater than the maximum allowed size. In future could be possible that  we will have a lot of parameter.

**Comment by ocboogie** [comment]
Yeah, that's a good concern. However, from what I have seen online, 2000 characters is around the limit which should be enough (at least, for now). For example,
 - 45 logbooks with 10 characters each: `45*10=450`
 - 20 tags with with 12 characters each: `20*12=240`
 - 2 dates with 27 characters each: `2*27=54`
 - URL path ~100 characters

All together, that's only around `844` characters. Of course, there will be more parameters and each parameter has characters for syntax (e.g., `,`, `&`, etc.),  so even if we multiply that by `1.5`, we're at `1266` characters which is still way below the limit.

**Comment by bisegni** [comment]
Yes totally agree!
@ocboogie you made a good analysis, I partially make the new api with few parameter when we have the overall parameter type I gonna to create the compete api for make the search

**Comment by ocboogie** [comment]
More reason having them in the URL: https://github.com/whatwg/fetch/issues/551
Apparently, having a body for GET requests is not in the spec for HTTP.

**Comment by bisegni** [comment]
yes i know the get cannot have the body, when and if we are facing that the 2xxx characters will be not enough we will try a solution 👍 
thank you
