### ISSUE TITLE
add shift management to the logbook

### ISSUE THREAD

**Issue by bisegni** [eed-web-application/elog-plus#71]

**Comment by ocboogie** [comment]
Suggested api changes:
1. Add `shift` (with the shift's name) to the `Entry` and `EntrySummary` DTOs
2. Add `GET /logbooks/{logbookId}/shifts` to get all the shifts in a logbook

This is all I need for now. However, once we we have the requirements for admin dashboard, we can talk about the necessary changes needed for that.

**Comment by bisegni** [comment]
the api for create new shift will be `POST /logbooks/{logbookId}/shifts`
