### ISSUE TITLE
Add endpoint `GET /shifts/{shiftId}/summaries/{yyyy-mm-dd}`

### ISSUE THREAD

**Issue by ocboogie** [eed-web-application/elog-plus#95]
`GET /shifts/{shiftId}/summaries/{yyyy-mm-dd}` will return the id of the summary of shift with id `shiftId` during the day `yyyy-mm-dd`. If no summary exists, then return with status 404.

**Comment by bisegni** [comment]
the ```{shiftId}``` will be the name of the shift
